version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_STACKS_IP
      APP_PORT: 3999
      PROXY_AUTH_WHITELIST: "/api/*"

  stacks-blockchain:
    image: ceramicwhite/stacks-blockchain:v2.05.0.3.0@sha256:953db9197b4615345f7e096d9e7b3a1b27a759a32a4be3190f6822064aa2dd18
    init: true
    restart: on-failure
    stop_grace_period: 1m
    #user: "1000:1000"
    command:
      [
        "/bin/stacks-node",
        "start",
        "--config",
        "/src/stacks-blockchain/Config.toml",
      ]
    ports:
      - $APP_STACKS_CORE_RPC_PORT:$APP_STACKS_CORE_RPC_PORT
      - $APP_STACKS_CORE_EVENT_PORT:$APP_STACKS_CORE_EVENT_PORT
    volumes:
      - ${APP_DATA_DIR}/persistent-data/stacks-blockchain:/root/stacks-node/data
      - ${APP_DATA_DIR}/stacks-node/config:/src/stacks-node
    networks:
      default:
        ipv4_address: $APP_STACKS_BLOCKCHAIN_IP

  stacks-blockchain-api:
    image: ceramicwhite/stacks-blockchain-api:v5.0.1@sha256:b7fb9fa5b1a7d65e583f2e2d9f10c8e20b31303772c4bd8734ad31618e4d86e9
    init: true
    restart: on-failure
    stop_grace_period: 1m
    environment:
      NODE_ENV: production
      PG_HOST: postgres
      PG_PORT: $APP_STACKS_DB_PORT
      PG_USER: "umbrel"
      PG_PASSWORD: "moneyprintergobrrr"
      PG_DATABASE: postgres
      STACKS_CHAIN_ID: 0x00000001
      V2_POX_MIN_AMOUNT_USTX: 90000000260
      STACKS_CORE_EVENT_PORT: 3700
      STACKS_CORE_EVENT_HOST: 0.0.0.0
      STACKS_BLOCKCHAIN_API_PORT: $APP_STACKS_API_PORT
      STACKS_BLOCKCHAIN_API_HOST: 0.0.0.0
      STACKS_BLOCKCHAIN_API_DB: pg
      STACKS_CORE_RPC_HOST: stacks-blockchain
      STACKS_CORE_RPC_PORT: ${APP_STACKS_CORE_RPC_PORT:-3700}
      #STACKS_API_ENABLE_FT_METADATA: 1
      #STACKS_API_ENABLE_NFT_METADATA: 1
      #BNS_IMPORT_DIR=/bns-data
      STACKS_EXPORT_EVENTS_FILE: /tmp/event-replay/stacks-node-events.tsv
    ports:
      - $APP_STACKS_CORE_EVENT_PORT:$APP_STACKS_CORE_EVENT_PORT
      - $APP_STACKS_API_PORT:$APP_STACKS_API_PORT
    networks:
      default:
        ipv4_address: $APP_STACKS_API_IP
    depends_on:
      - postgres

  postgres:
    image: postgres:13.7@sha256:03652c675ae177af98ddd50f9f4b4b2cf8ad38d0e116aa68fe670fbc2cf250fc
    restart: on-failure
    stop_grace_period: 1m
    #ports:
    #  - $APP_STACKS_DB_PORT:$APP_STACKS_DB_PORT
    volumes:
      - ${APP_DATA_DIR}/persistent-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: umbrel
      POSTGRES_PASSWORD: moneyprintergobrrr
      POSTGRES_DB: pg
      POSTGRES_PORT: $APP_STACKS_DB_PORT
    networks:
      default:
        ipv4_address: $APP_STACKS_DB_IP