version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_CRATER_IP
      APP_PORT: 3000
      
  web:
    image: ceramicwhite/crater:6.0.6@sha256:ae54c3a2d9f87f147e79fb96c053ea5b28b78fd6c7e5d263b27fd36b6f71e9f6
    restart: on-failure
    stop_grace_period: 1s
    user: crater
    init: true
    working_dir: /var/www/
    environment:
      uid: 1000
    volumes:
      - ${APP_DATA_DIR}/data/crater:/var/www
      - ${APP_DATA_DIR}/date/crater/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    depends_on:
      - mariadb
    networks:
      default:
        ipv4_address: $APP_CRATER_IP

  mariadb:
    image: mariadb:10.5.12@sha256:dfcba5641bdbfd7cbf5b07eeed707e6a3672f46823695a0d3aba2e49bbd9b1dd
    restart: on-failure
    user: "1000:1000"
    stop_grace_period: 1s
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: crater
    ports:
      - '33006:3306'
    networks:
      default:
        ipv4_address: $APP_CRATER_DB_IP
  cron:
    image: ceramicwhite/crater-cron:6.0.6@sha256:2df14897e7fcd281995e97e0dd698da70294f587791656487e7336662c1b7cca
    volumes:
      - ${APP_DATA_DIR}/data/crater:/var/www
    networks:
      default:
        ipv4_address: $APP_CRATER_CRON_IP
  nginx:
    image: nginx:1.19-alpine@sha256:07ab71a2c8e4ecb19a5a5abcfb3a4f175946c001c8af288b1aa766d67b0d05d2
    init: true
    restart: on-failure
    volumes:
      #- ${APP_DATA_DIR}/nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ${APP_DATA_DIR}/data/nginx/nginx.conf:/etc/nginx/conf.d/
      - ${APP_DATA_DIR}/data/crater/www:/var/www
    depends_on:
      - crater    
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/
      APP_CRATER_IP: $APP_CRATER_IP
      APP_CRATER_DB_IP: $APP_CRATER_DB_IP
      APP_CRATER_CRON_IP: $APP_CRATER_CRON_IP
    networks:
      default:
        ipv4_address: $APP_CRATER_IP